# Generated by Django 5.1.1 on 2024-10-18 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("loja", "0004_categoria_slug_tipo_slug"),
    ]

    operations = [
        migrations.RemoveField(model_name="itemestoque", name="cor",),
        migrations.RemoveField(model_name="itemestoque", name="tamanho",),
    ]
