# Generated by Django 5.1.2 on 2024-11-07 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0006_pagamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='altura',
            field=models.DecimalField(decimal_places=2, default=20, max_digits=5),
        ),
        migrations.AddField(
            model_name='produto',
            name='comprimento',
            field=models.DecimalField(decimal_places=2, default=20, max_digits=5),
        ),
        migrations.AddField(
            model_name='produto',
            name='largura',
            field=models.DecimalField(decimal_places=2, default=20, max_digits=5),
        ),
        migrations.AddField(
            model_name='produto',
            name='peso',
            field=models.DecimalField(decimal_places=2, default=3, max_digits=5),
        ),
    ]
