# Generated by Django 5.1.2 on 2024-11-21 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0008_avaliacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endereco',
            name='numero',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
